### ISSUE TITLE
Неверные опции

### ISSUE THREAD

**Issue by systemiv** [Brankub/selectik#11]
Ваш плагин предлагает установить класс контейнера, но при этом использует название дефолтного в коде.
Приведу пример, я задал в опциях containerClass: 'select-150'. В стилях естественно поменял, но не будет работать функция открытия/закрытия селекта так как надо из за этого:
if ($('.custom-select.open').length > 0){
И куча других строк.
В целом плагин мне понравился, нужно будет скрутить тоже свой, какие будут предложения по решению проблемы?

**Comment by Brankub** [comment]
Проблема решена. Хардкод убран.
