### ISSUE TITLE
Положение .select-list

### ISSUE THREAD

**Issue by radiocity** [Brankub/selectik#17]
Хотелось бы опцию, позволяющую отключать отображение .select-list над .custom-text

**Comment by Brankub** [comment]
Пожалуйста, уточните ваше пожелание. Опишите более конкретнее.

**Comment by radiocity** [comment]
Просто обязана существовать опция, позволяющая выпадать списку только вниз.
![Untitled-1](https://f.cloud.github.com/assets/2347073/5625/0c2e77b0-438a-11e2-92fb-ec40e77e9d09.png)
Иногда получается, что расположенные рядом selectы выпадают в разные стороны. (Один вверх, а другой вниз). Это не по фен-шую ^_^

**Comment by Brankub** [comment]
Сделано. При вызове плагина надо указать в настройках:
smartPosition: false

**Comment by radiocity** [comment]
Спасибо :)
