### ISSUE TITLE
Не до конца убирается оригинальный select

### ISSUE THREAD

**Issue by deltasem** [Brankub/selectik#2]
Код select'a
&lt;select id="Users" name="Users" style="width:100%;"&gt;
 &lt;option value="0"&gt;&lt;/option&gt;
 &lt;option value="747"&gt;Иванов4&lt;/option&gt;
 &lt;option value="770"&gt;Петров66&lt;/option&gt;
 &lt;option value="829"&gt;Петров&lt;/option&gt;
&lt;/select&gt;
<img src='http://img405.imageshack.us/img405/7294/41936571.png' />
<br/>
<img src='http://img11.imageshack.us/img11/383/77242950.png' />
<br/>
Google chrome 16.0.912.75 m

**Comment by Brankub** [comment]
Нынешняя stable версия 17. Ошибки не замечено.
