### ISSUE TITLE
Safari/OS X bug

### ISSUE THREAD

**Issue by Brankub** [Brankub/selectik#21]
Standard select showing after click on arrow.

**Comment by jmartsch** [comment]
This also happens when you are focussing the select field and then press the down arrow on the keyboard. Will you fix this fast?

**Comment by Brankub** [comment]
I'll try to fix this tomorrow.

**Comment by Brankub** [comment]
I've checked this problem in OS X. This issue appear only after keys (space, top/bottom arrows).
This is standard behaviour of select on Mac. We can't manipulate or change it like on Windows browsers. 

But we can shift standard select to the left border of custom for example:

<pre><code>.done select{
position: absolute:
left: 0px;
}
</code></pre>
