### ISSUE TITLE
Странно работает поиск с клавиатуры

### ISSUE THREAD

**Issue by derlaft** [Brankub/selectik#22]
Оно вроде работает, но только один раз. Т.е. если я нажму А и буду продолжать её щелкать, то я смогу двигаться по элементам, начинающимся с А, но если я нажму Б, то ничего не произойдет. 

Если открыть/закрыть фигульку, то можно опять искать. Но опять по одной букве.

FF18.0.2, Linux

**Comment by Brankub** [comment]
В демо примере выбирите "Show original selects".
Попробуйте сделать тоже только выбрав стандартный селект. Это нормальное поведение. Если вы быстро набираете - поиск идет по нескольким буквам(если находит совпадения), а если идет промежуток времени  - только ищет по первой.

**Comment by derlaft** [comment]
Похоже, что так и есть. Не знал, не знал %)
