### ISSUE TITLE
Does not work with latest version of jQuery (v1.9.1)

### ISSUE THREAD

**Issue by dsuriano** [Brankub/selectik#27]
Tried implementing Selectik with the latest version of jQuery (v1.9.1) and it broke. The issue was resolved by switching to jQuery v1.8.3.

Screenshot of the console error below: 

![2sd_](https://f.cloud.github.com/assets/633004/219541/d0dc0bda-8535-11e2-89f9-0a78496ac104.png)

**Comment by Brankub** [comment]
I will create new version of Selectik for 1.9.1+ jQuery library.

**Comment by muhammedjenos** [comment]
Also with 1.9.0 select.val(); doesnt return the real value of the option. I am not sure if this works with earlier versions of jquery. I really liked the plugin though and used on a live site. but after these issues, i had to remove it. :( Appreciate if you could fix this for the latest jquery

**Comment by Brankub** [comment]
Thank you for information, I am going to fix this issue till Monday.

**Comment by muhammedjenos** [comment]
Thants so nice of you bro. appreciate the hard work

**Comment by Brankub** [comment]
Now you can test it with 1.9.1+ jQuery library.
