### ISSUE TITLE
Отображается Value вместо текста 

### ISSUE THREAD

**Issue by deltasem** [Brankub/selectik#3]
Код:

&lt;select id="Users" name="Users" style="width:100%;"&gt;
 &lt;option value="0"&gt;&lt;/option&gt;
 &lt;option value="747"&gt;Иванов4&lt;/option&gt;
 &lt;option value="770"&gt;Петров66&lt;/option&gt;
 &lt;option value="829"&gt;Петров&lt;/option&gt;
&lt;/select&gt;
<img src="http://img33.imageshack.us/img33/8439/72936888.png"/>
<img src="http://img233.imageshack.us/img233/1258/60328698.png"/>
Google chrome 16.0.912.75 m

**Comment by germani** [comment]
строка 58
добавляем
textOption =$this.text()
строка 60 получается 
html += '<li class="'+disabled+'" data-value="'+valueOption+'">'+textOption+'</li>';
строка 70
меняем
$selected
на
$($selected).text()

строка 233
вместо
var dataValue = (e.parents('select').length > 0) ? e.attr('value') : e.data('value');

var dataValue = (e.parents('select').length > 0) ?  e.text() : e.text(); илии просто var dataValue = e.text();

ну вроде все...

**Comment by denys281** [comment]
@germani но $('#id_select').val(); не работает;

**Comment by germani** [comment]
@denys281 что такое #id_select

**Comment by denys281** [comment]
@germani  selectbox из id: id_select;

**Comment by germani** [comment]
значит не судьба )

**Comment by Brankub** [comment]
Исправлено. Закрыто.
