### ISSUE TITLE
Change event firing twice

### ISSUE THREAD

**Issue by pradeeprajudat** [Brankub/selectik#31]
I am using selectik and somehow when ever i change an option the change event is getting fired twice,,, here is an sample of what i am doing..

<  select id="selectiktest" onchange="fireevnt()"  >

function fireevnt(){
 console.log('change event fired');
}

$('#selectiktest').selectik();

i change an option and the console.log is printed twice

i am using jquery,,

**Comment by Brankub** [comment]
FIxed.
