### ISSUE TITLE
IE 7 and IE 8 support, 

### ISSUE THREAD

**Issue by acerosillo** [Brankub/selectik#35]
Is anyone else getting this same issue with IE7 and IE8 with the select input not appearing.

Below is a screenshot from IE7. Any solutions would help.

![img-b](https://f.cloud.github.com/assets/649264/682507/d75b588e-d9c8-11e2-9082-ecf344988cd7.jpg)
![img-a](https://f.cloud.github.com/assets/649264/682506/d7445044-d9c8-11e2-9731-dcccdbdf9076.jpg)

**Comment by paketep** [comment]
Yep, same here.

**Comment by Brankub** [comment]
Closed because this browsers not supported.
