### ISSUE TITLE
В iOS Safari немного странное поведение

### ISSUE THREAD

**Issue by raskumandrin** [Brankub/selectik#8]
При клике по плашке происходят одновременно две вещи:
1) разворачивается выпадающий список на веб-странице (синенький который)
2) вместе с ним включается стандартный (страшненький который такой) выбор для select'а (в интерфейсе браузера, а не сайта). этот второй и приходится использовать

после выбора элемента во втором варианте он выбирается, но синенький развёрнутый список сам не сворачивается.

**Comment by Brankub** [comment]
Да, я понимаю. В этом случае надо делать проверку на мобильные устройства.  Для минимизации кода я пока не реализовал этого. Будет отдельная версия с проверкой.
